# Delay, in seconds, that must be waited before teleportation of a player
# This time must be waited out without movement or taking damage
# Set to 0 for instant teleports
# Bypass permission: gbukkitlib.tpdelay.bypass
teleportDelay: 3

# Whether to show a countdown after the initial teleporting message
showIncrementalMessages: false

# The number of commands to display per base command help page
commandsPerPage: 10

# Messages displayed to users in-game
# Color codes are supported
# This is registered as a global MessageProvider service
messages:
  # Message to display to user when they are actually teleporting
  teleporting: "&6Teleportation commencing..."
  # Message to display to user when they are told they are starting the countdown to teleport
  # Keys replaced:
  # %time% - second(s) before teleportation will commence
  # %units% - "second" if %time% == 1, "seconds" otherwise
  teleportBegin: "&6Teleportation will commence in &c%time% %units%&6. Don't move."
  # Message to display to user after one second of the teleport delay has decayed
  # Keys replaced:
  # %time% - second(s) before teleportation will commence
  # %units% - "second" if %time% == 1, "seconds" otherwise
  teleportProgress: "&6Teleporting in &c%time% %units%&6."
  # Message to display to user if the teleport is cancelled.
  teleportCancelled: "&4Pending teleportation request cancelled."
  
  # Message for "see more" at the bottom of a base command help page
  # Keys replaced:
  # %basecommand% - the command without the slash
  # %page% - the next page number
  cmdHelpSeeMore: "&eType &6/%basecommand% help %page%&e to see more commands." 
  # Message for each command in a base command help page
  # Keys replaced:
  # %basecommand% - the command without the slash
  # %usage% - usage of the subcommand
  # %desc% - the description of the subcommand
  cmdHelpEntry: "&6/%basecommand% %usage% &7- &e%desc%"
  # Message to display when a user invokes an unknown subcommand
  cmdUnknown: "&cUnknown command."
  # Message to display when a user invokes a subcommand they can't use
  cmdNoPermission: "&cYou do not have access to that command."