 name: GBukkitCore
 version: ${project.version}
 description: This plugin is a library allowing uniform access to Bukkit functions used by multiple plugins, as well as other miscellaneous utilities.
 author: glen3b
 softdepend: [ProtocolLib]
 
 main: me.pagekite.glen3b.library.bukkit.GBukkitCorePlugin
 
 permissions:
   gbukkitcore.*:
     description: Allows all things
     children:
       gbukkitcore.config: true
       gbukkitcore.debug: true
       gbukkitcore.tpdelay.bypass: true
   gbukkitcore.tpdelay.bypass:
     description: Allows bypass of the teleportation delay
     default: op
   gbukkitcore.debug:
     description: Allows debug feature access
     default: op
   gbukkitcore.config:
     description: Allows config editing in-game
     default: op